# Generated by Django 4.0.4 on 2022-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodList', '0002_record_quantity_record_time_record_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(),
        ),
    ]
