# Generated by Django 4.0.4 on 2022-05-20 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodList', '0003_alter_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
